### PR TITLE
Added function to add DOM element

### PR DESCRIPTION
**Pull request by bragovo**
To use this lib with React (useRef) it will be nice to add elements by DOM (without query selectors).

### CODE REVIEW

**Comment by bragovo** [comment]
`yarn build` not changed lax.min.js :(

**Comment by bragovo** [comment]
Added min and gz versions

**Comment by arthurdenner** [comment]
Accordingly, we need a method to remove an element:

```js
removeElement = (domElement) => {
  this.elements = this.elements.filter(element => element.domElement !== domElement)
}
```

Would you mind adding it to this same PR, @bragovo? Otherwise, I can create one.

cc @alexfoxy

**Comment by bragovo** [comment]
Yeah, thanks, added to PR.

**Comment by bragovo** [comment]
@alexfoxy can you say something about this PR? Can you merge it?

**Pull request merged**
